spring:
  datasource:
    username: root
    password: liu123456
    url: jdbc:mysql://127.0.0.1:3306/smart_medicine?serverTimezone=Hongkong&useAffectedRows=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    username: 2205487298@qq.com
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    valid: 5
    title: "寻药就医系统 - 用户认证"
    template: "您的动态验证码为：<strong style='color: red'>%s</strong>，%d分钟内有效，若非本人操作，请勿泄露。"


  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  sendgrid:
    api-key: sk-xxxxxxxxxxxxxxx
  oss:
    bucket-name: xxxxxxxxxxx
    end-point: xxxxxxxxxxx
    access-key: xxxxxxxxxxxxxx
    access-secret: xxxxxxxxxxxx
